baseURL = 'https://Takumi-Sakamoto.github.io/webpage/'
languageCode = "jp"
DefaultContentLanguage = "jp"
title = 'Takumi Sakamoto'
canonifyurls = true
publishDir = "docs"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "Stacks"
author = "Takumi Sakamoto"
description = "Blogs about robotics and software"
profilePicture = "images/biwako.jpg"

  [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

  [[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"

  [[menu.main]]
    name = "Profile"
    weight = 300
    identifier = "profile"
    url = "/Profile/"