baseURL = 'https://Takumi-Sakamoto.github.io/webpage/'
languageCode = "jp"
DefaultContentLanguage = "jp"
title = 'Takumi Sakamoto'
canonifyurls = true
publishDir = "docs"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "個人wiki"
author = "Takumi Sakamoto"
profilePicture = "images/biwako.jpg"

  [[menu.main]]
    name = "Profile"
    weight = 300
    identifier = "profile"
    url = "/Profile/"